apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-externalsecret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: mysql-secret
    creationPolicy: Owner
  data:
    - secretKey: mysql-root-password
      remoteRef:
        key: p2/mysql-credentials
        property: root-password
    - secretKey: mysql-password
      remoteRef:
        key: p2/mysql-credentials
        property: wp-password
    - secretKey: mysql-user
      remoteRef:
        key: p2/mysql-credentials
        property: wp-user
    - secretKey: mysql-database
      remoteRef:
        key: p2/mysql-credentials
        property: wp-database
